language: c

compiler:
  - gcc

install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install dejagnu
  - sudo apt-get -qq install valgrind

script:
  - ./autogen.sh
  - ./configure
  - make
  - make check
